# SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note

ifeq (y, $(findstring y, $(CONFIG_ARCH_SA8155) $(CONFIG_ARCH_SA6155) $(CONFIG_ARCH_SA8195)))
else
header-y += msm_hdmi_hdcp_mgr.h
endif
