#define CONFIG_DRM_MSM_SDE 1
#define CONFIG_DRM_MSM_HYP 1
#define CONFIG_DRM_MSM_HYP_VIRTIO 1
#define CONFIG_SYNC_FILE 1
#define CONFIG_DRM_MSM_REGISTER_LOGGING 1
#define CONFIG_QCOM_MDSS_PLL 1
#define CONFIG_THERMAL_OF 1