# SPDX-License-Identifier: GPL-2.0-only

KDIR := $(TOP)/kernel_platform/msm-kernel
#soc-repo

ifeq ($(PLATFORM_VERSION), W Baklava 16)
ifeq (y, $(findstring y, $(CONFIG_ARCH_QTI_VM)))
	include $(DISPLAY_ROOT)/config/gvmdisp.conf
	LINUXINCLUDE += -include $(DISPLAY_ROOT)/config/gvmdispconf.h
endif
else
ifeq (y, $(findstring y, $(CONFIG_QTI_QUIN_GVM)))
	include $(DISPLAY_ROOT)/config/gvmdisp.conf
	LINUXINCLUDE += -include $(DISPLAY_ROOT)/config/gvmdispconf.h
endif
endif #Platform

CDEFINES +=	-DANI_LITTLE_BYTE_ENDIAN \
	-DANI_LITTLE_BIT_ENDIAN \
	-DDOT11F_LITTLE_ENDIAN_HOST \
	-DANI_COMPILER_TYPE_GCC \
	-DANI_OS_TYPE_ANDROID=6 \
	-DPTT_SOCK_SVC_ENABLE \
	-Wall\
	-Werror\
	-D__linux__

KBUILD_CPPFLAGS += $(CDEFINES)

ifeq ($(call cc-option-yn, -Wmaybe-uninitialized),y)
EXTRA_CFLAGS += -Wmaybe-uninitialized
endif

ifeq ($(call cc-option-yn, -Wheader-guard),y)
EXTRA_CFLAGS += -Wheader-guard
endif

ifneq ($(MODNAME), qdsp6v2)
CHIP_NAME ?= $(MODNAME)
CDEFINES += -DMULTI_IF_NAME=\"$(CHIP_NAME)\"
endif

#msm_cfg-y := msm_cfg.o

obj-$(CONFIG_DRM_MSM_CFG) += msm_cfg.o

CDEFINES += -DBUILD_TIMESTAMP=\"$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')\"
